#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
# Copyright (c) 2026 Craig Wright

"""Generate the realistic-quarter example data files deterministically.

Produces:
    records.json            48 invoices + 43 receipts + 1 credit note + 1
                            write-off as canonical record JSON, with each
                            record's leaf = double_sha256(record_bytes).
                            Suitable as input to `vaa anchor` / `vaa prove`.
    ar_rollforward.json     period totals for the AR roll-forward identity,
                            checked by direct recomputation over the
                            disclosed records.
    bundle_record_017.json  proof bundle for record #17, generated by
                            shelling out to the `vaa` CLI's `prove`
                            subcommand.

Re-run any time to regenerate from the deterministic seed in this file.
Requires the `vaa` binary on PATH (or $VAA).
"""

from __future__ import annotations

import hashlib
import json
import os
import subprocess
import sys
from pathlib import Path


HERE = Path(__file__).resolve().parent
SEED = b"verifiable-accounting/realistic_quarter/v2"


def double_sha256(b: bytes) -> bytes:
    return hashlib.sha256(hashlib.sha256(b).digest()).digest()


COUNTERPARTIES = [
    "Aurora Components",
    "Bracken Foundry",
    "Caldera Logistics",
    "Drumlin Press",
    "Elder Surveyors",
    "Felspar Brewing",
    "Gimbal Estates",
    "Heron Imports",
    "Indigo Labs",
    "Jasper Tooling",
    "Kelp Studios",
    "Larch Trading",
]

# 48 invoices, distributed across 12 counterparties (minor units).
INVOICES = []
for i in range(48):
    cp = COUNTERPARTIES[i % len(COUNTERPARTIES)]
    base = 400_000 + (i * 173_000) % 7_600_000
    INVOICES.append({"i": i, "counterparty": cp, "value": base})

RECEIPTS = [{"i": i, "value": INVOICES[i]["value"]} for i in range(43)]
CREDIT_NOTE = {"i": 17, "value": 1_800_000}
WRITE_OFF = {"i": 44, "value": 950_000}


def record_bytes(kind: str, ix: int, value: int, counterparty: str) -> bytes:
    obj = {
        "kind": kind,
        "id": ix,
        "value": int(value),
        "counterparty": counterparty,
    }
    return json.dumps(obj, separators=(",", ":"), sort_keys=True).encode("ascii")


def build_records() -> list[bytes]:
    out: list[bytes] = []
    for n in INVOICES:
        out.append(record_bytes("invoice", n["i"], n["value"], n["counterparty"]))
    for n in RECEIPTS:
        out.append(
            record_bytes(
                "receipt",
                n["i"],
                n["value"],
                COUNTERPARTIES[n["i"] % len(COUNTERPARTIES)],
            )
        )
    out.append(
        record_bytes(
            "credit_note",
            CREDIT_NOTE["i"],
            CREDIT_NOTE["value"],
            COUNTERPARTIES[CREDIT_NOTE["i"] % len(COUNTERPARTIES)],
        )
    )
    out.append(
        record_bytes(
            "write_off",
            WRITE_OFF["i"],
            WRITE_OFF["value"],
            COUNTERPARTIES[WRITE_OFF["i"] % len(COUNTERPARTIES)],
        )
    )
    return out


def write_records() -> Path:
    records = build_records()
    out = HERE / "records.json"
    payload = {
        "comment": "Realistic Q2-2026 close for the hypothetical entity Aurora Mid-Cap Services. "
                   "48 invoices, 43 receipts, 1 credit note, 1 write-off. Records in canonical "
                   "ledger order. Each record's leaf hash = double_sha256(record_bytes).",
        "period": "2026-04-01..2026-06-30",
        "units": "minor_units",
        "records_hex": [r.hex() for r in records],
    }
    out.write_text(json.dumps(payload, indent=2))
    return out


AR_OPEN = 18_200_000
TOTAL_INVOICES = sum(n["value"] for n in INVOICES)
TOTAL_RECEIPTS = sum(n["value"] for n in RECEIPTS)
TOTAL_CREDIT_NOTES = CREDIT_NOTE["value"]
TOTAL_WRITE_OFFS = WRITE_OFF["value"]
AR_CLOSE = (
    AR_OPEN + TOTAL_INVOICES - TOTAL_RECEIPTS - TOTAL_CREDIT_NOTES - TOTAL_WRITE_OFFS
)


def write_ar_rollforward() -> Path:
    out = HERE / "ar_rollforward.json"
    payload = {
        "entity": "Aurora Mid-Cap Services (hypothetical)",
        "period": "2026-04-01..2026-06-30",
        "units": "minor_units",
        "equation": "AR_close = AR_open + Invoices - Receipts - CreditNotes - WriteOffs",
        "lines": {
            "ar_open": AR_OPEN,
            "invoices": TOTAL_INVOICES,
            "receipts": TOTAL_RECEIPTS,
            "credit_notes": TOTAL_CREDIT_NOTES,
            "write_offs": TOTAL_WRITE_OFFS,
            "ar_close": AR_CLOSE,
        },
        "identity_check": {
            "lhs_ar_open_plus_invoices": AR_OPEN + TOTAL_INVOICES,
            "rhs_ar_close_plus_receipts_plus_credits_plus_writeoffs":
                AR_CLOSE + TOTAL_RECEIPTS + TOTAL_CREDIT_NOTES + TOTAL_WRITE_OFFS,
            "holds": (AR_OPEN + TOTAL_INVOICES)
                == (AR_CLOSE + TOTAL_RECEIPTS + TOTAL_CREDIT_NOTES + TOTAL_WRITE_OFFS),
        },
        "note": "Identity checked by direct recomputation over the disclosed records. "
                "Inclusion of each record on BSV is proved separately via the Merkle Proof "
                "Entity (Layer A); selective retrieval of a record discloses only that "
                "record's bytes (Layer B selective disclosure).",
    }
    out.write_text(json.dumps(payload, indent=2))
    return out


def write_bundle(records_path: Path) -> Path:
    vaa = os.environ.get("VAA", "vaa")
    out = HERE / "bundle_record_017.json"
    proc = subprocess.run(
        [
            vaa, "prove",
            "--records", str(records_path),
            "--index", "17",
            "--out", str(out),
        ],
        capture_output=True, text=True, check=False,
    )
    if proc.returncode != 0:
        sys.stderr.write(proc.stdout)
        sys.stderr.write(proc.stderr)
        raise SystemExit(f"vaa prove failed (exit {proc.returncode})")
    return out


def main() -> int:
    print("Generating realistic Q2-2026 example data ...")
    records_path = write_records()
    print(f"  wrote {records_path.name}   ({len(build_records())} records)")
    ar_path = write_ar_rollforward()
    print(f"  wrote {ar_path.name}")
    print(f"    AR_open  : {AR_OPEN:>14,d} (minor units)")
    print(f"    Invoices : {TOTAL_INVOICES:>14,d}")
    print(f"    Receipts : {TOTAL_RECEIPTS:>14,d}")
    print(f"    Credits  : {TOTAL_CREDIT_NOTES:>14,d}")
    print(f"    Writeoffs: {TOTAL_WRITE_OFFS:>14,d}")
    print(f"    AR_close : {AR_CLOSE:>14,d}")
    print(
        f"    identity holds: {(AR_OPEN + TOTAL_INVOICES) == (AR_CLOSE + TOTAL_RECEIPTS + TOTAL_CREDIT_NOTES + TOTAL_WRITE_OFFS)}"
    )
    bundle_path = write_bundle(records_path)
    print(f"  wrote {bundle_path.name}  (record #17, value {INVOICES[17]['value']:,d})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
