#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
# Copyright (c) 2026 Craig Wright

"""Generate the realistic-quarter example data files deterministically.

Produces:
    notes.json              — 48 invoice + 43 payment + 1 credit + 1 write-off
                              note hashes, in canonical block order.
    ar_rollforward.json     — line-by-line satoshi amounts + per-line blinding
                              factors for the AR roll-forward equation, ready
                              to feed into `vaa-accounting::ArRollForward`.
    bundle_invoice_017.json — proof bundle for invoice #17 (the 2,450,000-sat
                              invoice to Cobalt Networks). Generated by
                              shelling out to the `vaa` CLI; rebuilds the
                              bundle from notes.json + the invoice-17 blinding.

Re-run any time to regenerate from the deterministic seeds in this file.
Requires the `vaa` binary on PATH (or $VAA).
"""

from __future__ import annotations

import hashlib
import json
import os
import subprocess
import sys
from pathlib import Path


HERE = Path(__file__).resolve().parent
SEED = b"verifiable-accounting/realistic_quarter/v1"


def double_sha256(b: bytes) -> bytes:
    return hashlib.sha256(hashlib.sha256(b).digest()).digest()


def display_be(internal_le: bytes) -> str:
    return internal_le[::-1].hex()


def note_hash(kind: str, ix: int, body_extra: bytes = b"") -> str:
    """Deterministic leaf hash (display big-endian)."""
    payload = SEED + b"|" + kind.encode() + b"|" + ix.to_bytes(4, "big") + b"|" + body_extra
    return display_be(double_sha256(payload))


def blinding_hex(ix: int, label: str) -> str:
    """Deterministic 32-byte non-zero blinding factor."""
    seed = SEED + b"|blinding|" + label.encode() + b"|" + ix.to_bytes(4, "big")
    h = hashlib.sha256(seed).digest()
    # Ensure non-zero: vanishingly unlikely from SHA-256 but explicit.
    while h == b"\x00" * 32:
        h = hashlib.sha256(h).digest()
    return h.hex()


# -------------------------------------------------------------------------
# 1. Notes (the leaves)
# -------------------------------------------------------------------------

COUNTERPARTIES = [
    "Cobalt Networks", "Helix R&D", "Wytham Labs", "Bracken Foundry",
    "Lyra Imports", "Quill Estates", "Mistral Press", "Plover Studios",
    "Tern Surveyors", "Vesper Brewing", "Zephyr Tooling", "Onyx Logistics",
]

# 48 invoices, distributed across 12 counterparties.
INVOICES = []
for i in range(48):
    cp = COUNTERPARTIES[i % len(COUNTERPARTIES)]
    # Realistic spread of invoice sizes (in satoshis): 400k–8M.
    base = 400_000 + (i * 173_000) % 7_600_000
    INVOICES.append({"i": i, "counterparty": cp, "satoshis": base})

# 43 payments — first 43 invoices get paid in full.
PAYMENTS = [
    {"i": i, "satoshis": INVOICES[i]["satoshis"]} for i in range(43)
]

# 1 credit note for invoice #17, partial credit of 1,800,000 sat.
CREDIT_NOTE = {"i": 17, "satoshis": 1_800_000}

# 1 write-off of invoice #44 at 950,000 sat (full).
WRITE_OFF = {"i": 44, "satoshis": 950_000}


def build_notes() -> list[str]:
    """Build the leaves list in canonical order: invoices, payments, credit, write-off."""
    leaves: list[str] = []
    for n in INVOICES:
        body_extra = f"INV-{n['i']:03d}|{n['counterparty']}|{n['satoshis']}".encode()
        leaves.append(note_hash("invoice", n["i"], body_extra))
    for n in PAYMENTS:
        body_extra = f"PAY-{n['i']:03d}|{n['satoshis']}".encode()
        leaves.append(note_hash("payment", n["i"], body_extra))
    body_extra = f"CN-{CREDIT_NOTE['i']:03d}|{CREDIT_NOTE['satoshis']}".encode()
    leaves.append(note_hash("credit_note", CREDIT_NOTE["i"], body_extra))
    body_extra = f"WO-{WRITE_OFF['i']:03d}|{WRITE_OFF['satoshis']}".encode()
    leaves.append(note_hash("write_off", WRITE_OFF["i"], body_extra))
    return leaves


def write_notes() -> Path:
    leaves = build_notes()
    out = HERE / "notes.json"
    payload = {
        "comment": "Realistic Q2-2026 close for Helix Subsat Services Ltd. "
                   "48 invoices, 43 payments, 1 credit note, 1 write-off. "
                   "Leaves in canonical block order.",
        "period": "2026-04-01..2026-06-30",
        "leaves_display_be": leaves,
    }
    out.write_text(json.dumps(payload, indent=2))
    return out


# -------------------------------------------------------------------------
# 2. AR roll-forward equation inputs
# -------------------------------------------------------------------------

AR_OPEN = 18_200_000  # carried from prior period
TOTAL_INVOICES = sum(n["satoshis"] for n in INVOICES)
TOTAL_RECEIPTS = sum(n["satoshis"] for n in PAYMENTS)
TOTAL_CREDIT_NOTES = CREDIT_NOTE["satoshis"]
TOTAL_WRITE_OFFS = WRITE_OFF["satoshis"]
AR_CLOSE = AR_OPEN + TOTAL_INVOICES - TOTAL_RECEIPTS - TOTAL_CREDIT_NOTES - TOTAL_WRITE_OFFS


def write_ar_rollforward() -> Path:
    out = HERE / "ar_rollforward.json"
    payload = {
        "entity": "Helix Subsat Services Ltd. (hypothetical)",
        "period": "2026-04-01..2026-06-30",
        "units": "satoshis",
        "equation": "AR_close = AR_open + Invoices - Receipts - CreditNotes - WriteOffs",
        "lines": {
            "ar_open":      {"satoshis": AR_OPEN,           "blinding_hex": blinding_hex(0, "ar_open")},
            "invoices":     {"satoshis": TOTAL_INVOICES,    "blinding_hex": blinding_hex(0, "invoices")},
            "receipts":     {"satoshis": TOTAL_RECEIPTS,    "blinding_hex": blinding_hex(0, "receipts")},
            "credit_notes": {"satoshis": TOTAL_CREDIT_NOTES,"blinding_hex": blinding_hex(0, "credit_notes")},
            "write_offs":   {"satoshis": TOTAL_WRITE_OFFS,  "blinding_hex": blinding_hex(0, "write_offs")},
            "ar_close":     {"satoshis": AR_CLOSE,          "blinding_hex": blinding_hex(0, "ar_close")},
        },
        "identity_check": {
            "lhs_ar_open_plus_invoices": AR_OPEN + TOTAL_INVOICES,
            "rhs_ar_close_plus_receipts_plus_credits_plus_writeoffs":
                AR_CLOSE + TOTAL_RECEIPTS + TOTAL_CREDIT_NOTES + TOTAL_WRITE_OFFS,
            "holds": (AR_OPEN + TOTAL_INVOICES) == (
                AR_CLOSE + TOTAL_RECEIPTS + TOTAL_CREDIT_NOTES + TOTAL_WRITE_OFFS
            ),
        },
        "note": "Blinding factors are deterministic for example reproducibility; "
                "production blindings MUST come from a CSPRNG.",
    }
    out.write_text(json.dumps(payload, indent=2))
    return out


# -------------------------------------------------------------------------
# 3. Worked proof bundle for invoice #17
# -------------------------------------------------------------------------


def write_bundle(notes_path: Path) -> Path:
    vaa = os.environ.get("VAA", "vaa")
    out = HERE / "bundle_invoice_017.json"
    inv17 = INVOICES[17]
    blinding = blinding_hex(17, "invoice-line")
    proc = subprocess.run(
        [
            vaa, "prove",
            "--leaves", str(notes_path),
            "--index", "17",
            "--value", str(inv17["satoshis"]),
            "--blinding-hex", blinding,
            "--out", str(out),
        ],
        capture_output=True, text=True, check=False,
    )
    if proc.returncode != 0:
        sys.stderr.write(proc.stdout)
        sys.stderr.write(proc.stderr)
        raise SystemExit(f"vaa prove failed (exit {proc.returncode})")
    return out


# -------------------------------------------------------------------------
# main
# -------------------------------------------------------------------------

def main() -> int:
    print("Generating realistic Q2-2026 example data ...")
    notes_path = write_notes()
    print(f"  wrote {notes_path.name}    ({len(build_notes())} leaves)")
    ar_path = write_ar_rollforward()
    print(f"  wrote {ar_path.name}")
    print(f"    AR_open  : {AR_OPEN:>12,d} sat")
    print(f"    Invoices : {TOTAL_INVOICES:>12,d} sat")
    print(f"    Receipts : {TOTAL_RECEIPTS:>12,d} sat")
    print(f"    Credits  : {TOTAL_CREDIT_NOTES:>12,d} sat")
    print(f"    Writeoffs: {TOTAL_WRITE_OFFS:>12,d} sat")
    print(f"    AR_close : {AR_CLOSE:>12,d} sat")
    print(f"    identity holds: {(AR_OPEN + TOTAL_INVOICES) == (AR_CLOSE + TOTAL_RECEIPTS + TOTAL_CREDIT_NOTES + TOTAL_WRITE_OFFS)}")
    bundle_path = write_bundle(notes_path)
    print(f"  wrote {bundle_path.name}    (invoice #17, {INVOICES[17]['satoshis']:,d} sat to {INVOICES[17]['counterparty']})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
